version: 2

defaults: &defaults
  docker:
    - image: circleci/node:8.2.1
  working_directory: ~/monorepo-builds

jobs:
  clone_and_hash:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-project-metadata-{{ .Branch }}
            - v1-project-metadata-master

      - run:
          name: Copy old hashes to shared workspace
          command: |
            mkdir -p .project-metadata
            touch .project-{a,b}-hash
            cp .project-a-hash .project-metadata
            cp .project-b-hash .project-metadata

      - run:
          name: Hash projects
          command: |
            git log --pretty=format:'%H' -n 1 -- project_a > .project-metadata/.project-a-hash.new
            git log --pretty=format:'%H' -n 1 -- project_b > .project-metadata/.project-b-hash.new

      - run:
          name: Determine changed projects
          command: |
            if ! diff .project-metadata/.project-a-hash{,.new}; then
              touch .project-metadata/.project-a-changed
            fi

            if ! diff .project-metadata/.project-b-hash{,.new}; then
              touch .project-metadata/.project-b-changed
            fi

      - run:
          name: Set current project hashes
          command: |
            mv .project-metadata/.project-a-hash{.new,}
            mv .project-metadata/.project-b-hash{.new,}

      - persist_to_workspace:
          root: .
          paths:
            - .project-metadata

      - save_cache:
          key: v1-project-metadata-{{ .Branch }}-{{ epoch }}
          paths:
            - .project-metadata/.project-a-hash
            - .project-metadata/.project-b-hash

  project_a:
    <<: *defaults
    working_directory: ~/monorepo-builds/project_a
    steps:
      - checkout: { path: ~/monorepo-builds }
      - attach_workspace: { at: . }
      - run:
          name: Check whether project changed
          command: |
            if [ -e .project-metadata/.project-a-changed ]; then
              echo "let's do this"
            else
              echo "nothing to do"
            fi

      - run:
          name: Install dependencies
          command: echo "install"

      - run:
          name: Build
          command: echo "Building Project A"

      - run:
          name: Test
          command: echo "Testing Project A"

      - run:
          name: Deployment
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Deploying Project A"
            fi

  project_b:
    <<: *defaults
    working_directory: ~/monorepo-builds/project_b
    steps:
      - checkout: { path: ~/monorepo-builds }
      - attach_workspace: { at: . }
      - run:
          name: Check whether project changed
          command: |
            if [ -e .project-metadata/.project-b-changed ]; then
              echo "let's do this"
            else
              echo "nothing to do"
            fi

      - run:
          name: Install dependencies
          command: echo "install"

      - run:
          name: Build
          command: echo "Building Project B"

      - run:
          name: Test
          command: echo "Testing Project B"

      - run:
          name: Deployment
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Deploying Project B"
            fi

workflows:
  version: 2

  build_test_deploy:
    jobs:
      - clone_and_hash
      - project_a:
          requires:
            - clone_and_hash
      - project_b:
          requires:
            - clone_and_hash
